language: rust
cache: cargo
sudo: required

rust:
- 1.22.0
- stable
- beta
- nightly
matrix:
  allow-failures:
  - rust: nightly

before_script:
- which cargo-make || cargo install cargo-make

script:
- cargo make ci-flow
