language: rust
cache: cargo

rust:
- 1.31.0
- stable
- nightly
matrix:
  allow-failures:
  - rust: nightly

before_script:
- which cargo-coverage-annotations && cargo-cargo-annotations --version
- cargo-install cargo-cargo-annotations --force
- cargo-cargo-annotations --version
- which cargo-make || cargo install cargo-make

script:
- cargo make ci-flow
