language: rust
cache: cargo

rust:
- stable
- nightly
matrix:
  allow-failures:
  - rust: nightly

before_script:
- which cargo-make || cargo install cargo-make

script:
- cargo make ci

after_success:
- curl -s https://codecov.io/bash | bash
