# Rust project
language: rust
cache: cargo

rust:
- 1.13.0
- stable
- beta
- nightly
matrix:
  allow-failures:
  - rust: nightly

# Build & Test
script:
- cargo build --verbose
- cargo test --verbose
