language: rust
cache: cargo

rust:
- 1.31.0
- stable
- nightly
matrix:
  allow-failures:
  - rust: nightly

before_script:
- which cargo-coverage-annotations && cargo-coverage-annotations --version
- cargo install cargo-coverage-annotations --version 0.2.1 --force
- cargo-coverage-annotations --version
- which cargo-make || cargo install cargo-make

script:
- cargo make ci-flow
