language: rust
cache: cargo
sudo: required

rust:
- 1.31.0
- stable
- nightly
matrix:
  allow-failures:
  - rust: nightly

before_script:
- which cargo-make || cargo install cargo-make
- rustup install nightly
- cargo +nightly install --force rustfmt-nightly

script:
- cargo make ci-flow
