# TODO: Add this to the ci-flow when rustfmt starts working on Travis.
[tasks.verify-format]
description = "Verify the code is formatted as expected by rustfmt."
install_crate = "rustfmt-nightly"
command = "cargo"
args = ["fmt", "--", "--write-mode", "diff"]

[tasks.format]
dependencies = ["format-nightly"]
